version: "3.8"

networks:
  inception:
    name: inception

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./requirements/wordpress/data
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./requirements/mariadb/data3

services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
    env_file: .env
    ports:
      - "8443:8443"
    restart: on-failure

  mariadb:
    container_name: mariadb
    networks:
    - inception
    build: 
     context: requirements/mariadb
    env_file: .env
    volumes:
    - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress_data:/var/www/wordpress
    networks:
    - inception
    build: 
      context: requirements/wordpress
    depends_on:
    - mariadb
    restart: on-failure
    ports:
      - "9000:9000"
