version: "3.5"

networks:
  inception:
    name: inception

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/amirloup/Documents/Inception/srcs/requirements/wordpress
  # mariadb_data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/amirloup/Documents/Inception/srcs/requirements/mariadb

services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
    # dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8443:8443"
    restart: on-failure

  mariadb:
    container_name: mariadb
    networks:
    - inception
    build: 
     context: requirements/mariadb
    # dockerfile: Dockerfile
    env_file: .env
    # volumes:
    # - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    expose:
    - "3306"

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress_data:/var/www/wordpress
    networks:
    - inception
    build: 
      context: requirements/wordpress
    # dockerfile: Dockerfile
    depends_on:
    - mariadb
    restart: on-failure
    expose: 
    - "9000"

